version: '2'
services:

   node:
     user: "${USERID}:${GROUPID}"
     image: node:12.4.0
     volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - "${JENKINS_HOME}:${JENKINS_HOME}:rw"
      - "${WORKSPACE}:${WORKSPACE}:rw"
     environment:
      NEXUS_USERNAME: $NEXUS_USERNAME
      NEXUS_PASSWORD: $NEXUS_PASSWORD
